src/StCamillus/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace StCamillus.Models
{
    // Add profile data for application users by adding properties to the ApplicationUser class
    public class ApplicationUser : IdentityUser
    {

    }
}

src/StCamillus/Controllers/ApplicationUsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StCamillus.Data;
using StCamillus.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;

namespace StCamillus.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "User Admin")]
    public class ApplicationUsersController : Controller
    {
        private const string UserAdminRole = "User Admin";

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ApplicationUsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            var models = new List<ApplicationUsersIndexViewModel>();
            var users = await _context.ApplicationUser.ToListAsync();
            foreach (var user in users)
            {
                models.Add(new ApplicationUsersIndexViewModel(_userManager) { ApplicationUser = user });
            }
            return View(models);
        }

        // GET: ApplicationUsers/DisableLock/5s
        public async Task<IActionResult> DisableLock(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleAsync(u => u.Id == id);
            var result = await _userManager.SetLockoutEnabledAsync(applicationUser, false);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangeUserRole(string id, string direction, string role)
        {
            var applicationUser = await _context.ApplicationUser.SingleAsync(u => u.Id == id);
            switch (direction)
            {
                case "Enable": { await _userManager.AddToRoleAsync(applicationUser, role); break; }
                case "Disable": { await _userManager.RemoveFromRoleAsync(applicationUser, role); break; }
            }
            return RedirectToAction("Index");
        }

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("firstrun")]
        [AllowAnonymous]
        public async Task<IActionResult> CreateRolesAndAdminUsers()
        {
            await EnsureRolesCreated();
            await EnsureUserAdminUsersCreated();
            return Ok("Roles and Admins created");
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
        private async Task EnsureUserAdminUsersCreated( )
        {
            var users = new List<ApplicationUser>
            {
                new ApplicationUser { Email = "sha57@verizon.net"},
                new ApplicationUser { Email = "david.droddy@gmail.com"},
                new ApplicationUser { Email = "yaojen.lu@gmail.com"}
            };

            foreach ( var user in users )
            {
                user.UserName = user.Email;
                var adminUser = await _userManager.FindByNameAsync( user.UserName );

                if ( adminUser == null )
                {
                    var result = await _userManager.CreateAsync( user, "***" );

                    adminUser = await _userManager.FindByNameAsync( user.UserName );
                    if ( adminUser != null )
                    {
                        if ( await _roleManager.RoleExistsAsync( UserAdminRole ) &&
                            ! await _userManager.IsInRoleAsync( adminUser, UserAdminRole ) )
                        {
                            await _userManager.AddToRoleAsync( adminUser, UserAdminRole );
                        }
                    }
                }
            }
        }
        private async Task EnsureRolesCreated( )
        {
            var roles = new List<IdentityRole>
            {
                new IdentityRole {Name = UserAdminRole},
                new IdentityRole {Name = "Standard User"},
                new IdentityRole {Name = "Silver Spring"},
                new IdentityRole {Name = "Langley Park"}
            };

            foreach ( var role in roles )
            {
                var roleExists = await _roleManager.RoleExistsAsync( role.Name.ToUpper() );
                if ( !roleExists )
                {
                    var result = await _roleManager.CreateAsync( role );
                }
            }
        }

    }
}

src/StCamillus/Views/ApplicationUsers/Create.cshtml
@model StCamillus.Models.ApplicationUser

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>ApplicationUser</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <label asp-for="AccessFailedCount" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="AccessFailedCount" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ConcurrencyStamp" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="ConcurrencyStamp" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Email" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="Email" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <div class="checkbox">
                    <input asp-for="EmailConfirmed" />
                    <label asp-for="EmailConfirmed"></label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <div class="checkbox">
                    <input asp-for="LockoutEnabled" />
                    <label asp-for="LockoutEnabled"></label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="LockoutEnd" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="LockoutEnd" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NormalizedEmail" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="NormalizedEmail" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NormalizedUserName" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="NormalizedUserName" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="PasswordHash" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="PasswordHash" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="PhoneNumber" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="PhoneNumber" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <div class="checkbox">
                    <input asp-for="PhoneNumberConfirmed" />
                    <label asp-for="PhoneNumberConfirmed"></label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="SecurityStamp" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="SecurityStamp" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <div class="checkbox">
                    <input asp-for="TwoFactorEnabled" />
                    <label asp-for="TwoFactorEnabled"></label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="UserName" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="UserName" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/StCamillus/Views/ApplicationUsers/Delete.cshtml
@model StCamillus.Models.ApplicationUser

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ConcurrencyStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ConcurrencyStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LockoutEnd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NormalizedEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NormalizedEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NormalizedUserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NormalizedUserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/StCamillus/Views/ApplicationUsers/Details.cshtml
@model StCamillus.Models.ApplicationUser

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ApplicationUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LockoutEnd)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/StCamillus/Views/ApplicationUsers/Edit.cshtml
@model StCamillus.Models.ApplicationUser

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>ApplicationUser</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group row">
            <label asp-for="AccessFailedCount" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="AccessFailedCount" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Email" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="Email" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <div class="checkbox">
                    <input asp-for="EmailConfirmed" />
                    <label asp-for="EmailConfirmed"></label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <div class="checkbox">
                    <input asp-for="LockoutEnabled" />
                    <label asp-for="LockoutEnabled"></label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="LockoutEnd" class="col-lg-2 col-form-label"></label>
            <div class="col-lg-10">
                <input asp-for="LockoutEnd" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-lg-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/StCamillus/Views/ApplicationUsers/Index.cshtml
@model IEnumerable<StCamillus.Models.ApplicationUsersIndexViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Users</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser.Email)
            </th>
            <th>User Admin</th>
            <th>Silver Spring</th>
            <th>Langley Park</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (ApplicationUsersIndexViewModel item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
                </td>
                <td>@item.UserAdminToggleBool <a title="@item.UserAdminToggleToolTip User Admin Role" asp-action="ChangeUserRole" asp-controller="ApplicationUsers" asp-route-id="@item.ApplicationUser.Id" asp-route-direction="@item.UserAdminToggleVerb" asp-route-role="User Admin">@item.UserAdminToggleVerb</a></td>
                <td>@item.SilverSpringToggleBool <a title="@item.SilverSpringToggleToolTip Silver Spring Role" asp-action="ChangeUserRole" asp-controller="ApplicationUsers" asp-route-id="@item.ApplicationUser.Id" asp-route-direction="@item.SilverSpringToggleVerb" asp-route-role="Silver Spring">@item.SilverSpringToggleVerb</a></td>
                <td>@item.LangleyParkToggleBool <a title="@item.LangleyParkToggleToolTip Langley Park Role" asp-action="ChangeUserRole" asp-controller="ApplicationUsers" asp-route-id="@item.ApplicationUser.Id" asp-route-direction="@item.LangleyParkToggleVerb" asp-route-role="Langley Park">@item.LangleyParkToggleVerb</a></td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.ApplicationUser.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>