src/StCamillus/Models/Demographic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StCamillus.Models
{
    public partial class Demographic
    {
        public Demographic()
        {
            DemographicMultiValue = new HashSet<DemographicMultiValue>();
            Distributions = new HashSet<Distribution>();
        }

        [Display(Name = "Demographic Id")]
        public int DemographicId { get; set; }

        [Display(Name = "Last Name"), Required]
        public string LastName { get; set; }

        [Display(Name = "First Name"), Required]
        public string FirstName { get; set; }

        [Display(Name = "Address")]
        public string StreetAddress { get; set; }

        [Display(Name = "City")]
        public string City { get; set; }

        [Display(Name = "State")]
        public int? StateId { get; set; }

        [Display(Name = "County")]
        public int? CountyId { get; set; }

        [Display(Name = "Zip Code")]
        public string ZipCode { get; set; }

        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Country of Origin")]
        public int? OriginCountryId { get; set; }

        [Display(Name = "Ethnicity")]
        public int? EthnicityId { get; set; }

        [Display(Name = "Marriage Status")]
        public int? MarriageStatusId { get; set; }

        [Display(Name = "Number of People in Family")]
        public short? TotalFamilyMembers { get; set; }

        public short? Adults { get; set; }

        [Display(Name = "0-2 years")]
        public bool ChildrenZeroToTwo { get; set; }

        [Display(Name = "3-5 years")]
        public bool ChildrenThreeToFive { get; set; }

        [Display(Name = "6-14 years")]
        public bool ChildrenSixToFourteen { get; set; }

        [Display(Name = "15-18 years")]
        public bool ChildrenFifteenToEighteen { get; set; }

        public string Note { get; set; }

        [Display(Name = "2018 MD Self Disclosure Form")]
        public bool SelfDisclosure { get; set; }

        public short? Children { get; set; }

        //there has been a problem with client-side date validation
        //where, if you set the model DataType attribute to Date, this enables HTML 5 client-side validation
        //but if you want to use something like jQuery UI's datepicker (more compatability) the Date DataType will work
        //but then you have both the HTML5 picker combined with the jQuery UI picker and there is also the chance that the HTML 5 date format won't agree 
        //with the format jQuery UI is setup for
        //jQuery UI Date Picker
        //[DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        //let's try html 5 again
        [DataType(DataType.Date)]
        [Display(Name = "* Date of Birth")]
        public DateTime? Dob { get; set; }

        [DisplayFormat(DataFormatString = "{0:D}")]
        [Display(Name = "Age")]
        public int? FlattenedAge { get { return Convert.ToInt32( Age ?? Age ); } }

        public decimal? Age { get; set; }

        [Display(Name = "Bi-weekly Income")]
        public int? BiWeeklyIncomeId { get; set; }

        [Display(Name = "Card ID"), Required]
        public int? BarcodeId { get; set; }

        public virtual ICollection<DemographicMultiValue> DemographicMultiValue { get; set; }

        public virtual ICollection<Distribution> Distributions { get; set; }

        public virtual MannaData MannaData { get; set; }

        public virtual LookupValue BiWeeklyIncome { get; set; }

        public virtual LookupValue County { get; set; }

        public virtual LookupValue Ethnicity { get; set; }

        public virtual LookupValue MarriageStatus { get; set; }

        public virtual LookupValue OriginCountry { get; set; }

        public virtual LookupValue State { get; set; }
    }
}

src/StCamillus/Controllers/MannaDataController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StCamillus.Models;
using Microsoft.AspNetCore.Authorization;

namespace StCamillus.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "User Admin, Silver Spring, Langley Park")]
    public class MannaDataController : Controller
    {
        private readonly StCamillusContext _context;

        public MannaDataController(StCamillusContext context)
        {
            _context = context;    
        }

        public IActionResult AddEditByDemographicId( int? id )
        {
            if ( id == null )
            {
                return NotFound();
            }

            var mannaData = _context.MannaData.FirstOrDefault( md => md.DemographicId == id );

            int? mannaDataId = mannaData?.MannaDataId;

            return mannaDataId == null ? Create( id ).Result : RedirectToAction( "Edit", new { id = mannaDataId } );
        }

        // GET: MannaData
        //public async Task<IActionResult> Index()
        //{
        //    var stCamillusContext = _context.MannaData.Include(m => m.BabyFoodStage).Include(m => m.Demographic).Include(m => m.EmploymentStatus).Include(m => m.Gender).Include(m => m.Race).Include(m => m.Transportation);
        //    return View(await stCamillusContext.ToListAsync());
        //}

        // GET: MannaData/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mannaData = await _context.MannaData.SingleOrDefaultAsync(m => m.MannaDataId == id);
            if (mannaData == null)
            {
                return NotFound();
            }

            return View(mannaData);
        }

        // GET: MannaData/Create/5
        //id is the Demographic ID this mannadata should be linked to
        private async Task<IActionResult> Create(int? id)
        {
            ViewBag.ChangesMade = false;
            if (id == null)
            {
                return NotFound();
            }

            if (!_context.Demographic.Any(d => d.DemographicId == id))
            {
                return NotFound();
            }

            var mannaData = new MannaData { DemographicId = id.Value };
            _context.Add(mannaData);
            await _context.SaveChangesAsync();
            var newId = _context.MannaData.FirstOrDefaultAsync(m => m.DemographicId == id).Result.MannaDataId;
            return RedirectToAction("Edit", new { id = newId, newRecord = true });
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("BabyFoodStageId,DemographicId,EmailAddress,EmergencyContactName,EmergencyContactPhone,EmploymentStatusId,FoodStampDollars,FormulaType,GenderId,IsEmployed,IsReceivingEnergyAssistance,IsUsingMedicaid,MonthlyGrossDollars,NeedsDiabeticBox,NeedsVegetarianBox,NumberOfChildren,OtherDollars,PrimaryLanguage,RaceId,SocialSecurityDisabilityInsuranceDollars,SocialSecurityInsuranceDollars,Tanfdollars,TransportationId,UnemploymentDollars,YearlyGrossDollars")] MannaData mannaData)
        //{
        //    ViewBag.ChangesMade = false;
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(mannaData);
        //        await _context.SaveChangesAsync();

        //        var newMannaData = await _context.MannaData.FirstOrDefaultAsync(m => m.DemographicId == mannaData.DemographicId);

        //        return RedirectToAction("Edit", new { id = newMannaData.MannaDataId, newRecord = true });
        //    }
        //    AddSelectLists();
        //    return View(mannaData);
        //}

        // GET: MannaData/Edit/5
        public async Task<IActionResult> Edit(int? id, bool newRecord = false)
        {
            ViewBag.ChangesMade = false;
            if (id == null)
            {
                return NotFound();
            }

            var mannaData = await _context.MannaData.Where(m => m.MannaDataId == id).Include(m => m.Demographic).Include(m => m.Demographic.Ethnicity).Include(m => m.MannaPickups).FirstOrDefaultAsync();
            if (mannaData == null)
            {
                return NotFound();
            }

            ViewBag.NewMannaDataCreated = newRecord;
            AddEthnicityToViewModel(mannaData);
            AddPickupLocationsToViewModel(mannaData);
            AddSelectLists();
            return View(mannaData);
        }

        // POST: MannaData/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( int id, [Bind( "MannaDataId,BabyFoodStageId,DemographicId,EmailAddress,EmergencyContactName,EmergencyContactPhone,EmploymentStatusId,FoodStampDollars,FormulaType,GenderId,IsEmployed,IsReceivingEnergyAssistance,IsUsingMedicaid,MonthlyGrossDollars,NeedsDiabeticBox,NeedsVegetarianBox,NumberOfChildren,OtherDollars,PrimaryLanguage,RaceId,SocialSecurityDisabilityInsuranceDollars,SocialSecurityInsuranceDollars,Tanfdollars,TransportationId,UnemploymentDollars,YearlyGrossDollars" )] MannaData mannaData )
        {
            ViewBag.NewMannaDataCreated = false;
            ViewBag.ChangesMade = false;
            if ( id != mannaData.MannaDataId )
            {
                return NotFound();
            }

            if ( ModelState.IsValid )
            {
                try
                {
                    _context.Update( mannaData );
                    await _context.SaveChangesAsync();
                }
                catch ( DbUpdateConcurrencyException )
                {
                    if ( !MannaDataExists( mannaData.MannaDataId ) )
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.ChangesMade = true;
            }

            var dbMannaData = await _context.MannaData.Where( m => m.MannaDataId == id ).Include( m => m.Demographic ).Include( m => m.Demographic.Ethnicity ).Include( m => m.MannaPickups ).FirstOrDefaultAsync();
            if ( dbMannaData == null )
            {
                return NotFound();
            }

            mannaData.Demographic = dbMannaData.Demographic;
            AddEthnicityToViewModel( mannaData );

            AddSelectLists();
            return View( mannaData );
        }

        private void AddPickupLocationsToViewModel(MannaData mannaData)
        {
            foreach (var pickup in mannaData.MannaPickups)
            {
                pickup.PickupLocation = _context.LookupValue.FirstOrDefaultAsync(l => l.LookupValueId == pickup.PickupLocationId).Result;
            }
        }

        private void AddEthnicityToViewModel(MannaData mannaData)
        {
            const string hispanicLatino = "Hispanic/Latino";
            ViewData["Ethnicity"] = mannaData.Demographic.Ethnicity?.Description == "Hispanic"
                ? hispanicLatino
                : string.Format("Not {0}", hispanicLatino);
        }

        //// GET: MannaData/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var mannaData = await _context.MannaData.SingleOrDefaultAsync(m => m.MannaDataId == id);
        //    if (mannaData == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(mannaData);
        //}

        // POST: MannaData/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var mannaData = await _context.MannaData.SingleOrDefaultAsync(m => m.MannaDataId == id);
        //    _context.MannaData.Remove(mannaData);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        private bool MannaDataExists(int id)
        {
            return _context.MannaData.Any(e => e.MannaDataId == id);
        }

        private void AddSelectLists()
        {
            ViewData["BabyFoodStages"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(10)), "LookupValueId", "Description");
            ViewData["Genders"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(11)), "LookupValueId", "Description");
            ViewData["EmploymentStatuses"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(12)), "LookupValueId", "Description");
            ViewData["Races"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(13)), "LookupValueId", "Description");
            ViewData["ModesOfTransportation"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(14)), "LookupValueId", "Description");
        }
    }
}

src/StCamillus/Views/Demographics/Create.cshtml
@model DemographicAddEditViewModel

@{
    ViewData[ "Title" ] = "Household";
    ViewBag.AddEditMode = "Add";
}

<h2>
    @ViewData[ "Title" ]
    <small class="text-muted"> - Add</small>
</h2>

<form asp-action="Create" class="dataEntry loader">

    @Html.Partial( "_AddEditPartial" )

</form>

@section scripts{
    @{await Html.RenderPartialAsync( "_ValidationScriptsPartial" );}

    @*<script>
        $(function () {
            $(".jqueryui-marker-datepicker").datepicker({
                changeYear: true,
                yearRange: "-100:+0"
            });
        });</script>*@
}

src/StCamillus/Views/Demographics/Delete.cshtml
@model StCamillus.Models.Demographic

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Demographic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adults)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Adults)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BarcodeId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BarcodeId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Children)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Children)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ChildrenFifteenToEighteen)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ChildrenFifteenToEighteen)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ChildrenSixToFourteen)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ChildrenSixToFourteen)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ChildrenThreeToFive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ChildrenThreeToFive)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ChildrenZeroToTwo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ChildrenZeroToTwo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dob)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dob)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SelfDisclosure)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SelfDisclosure)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalFamilyMembers)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalFamilyMembers)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @*<a asp-action="Index">Back to List</a>*@
        </div>
    </form>
</div>

src/StCamillus/Views/Demographics/Edit.cshtml
@model DemographicAddEditViewModel

@{
    ViewData[ "Title" ] = "Household";
    ViewBag.AddEditMode = "Edit";
}

<h2>
    @ViewData[ "Title" ]
    <small class="text-muted"> - Edit</small>
</h2>

<form asp-action="Edit" class="dataEntry loader">

    @Html.Partial( "_AddEditPartial" )

</form>

@section scripts{
    @{await Html.RenderPartialAsync( "_ValidationScriptsPartial" );}

    @*<script>
        $(function () {
            $(".jqueryui-marker-datepicker").datepicker({
                changeYear: true,
                yearRange: "-100:+0"
            });
        });</script>*@
}

src/StCamillus/Views/Demographics/Index.cshtml
@model IEnumerable<StCamillus.Models.Demographic>

@{
    ViewData["Title"] = "Index";
}

<h2>Households</h2>

<p>
    <a class="btn btn-outline-dark" asp-action="Create">Click here to Add a New Household</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor( model => model.LastName )
            </th>
            <th>
                @Html.DisplayNameFor( model => model.FirstName )
            </th>
            <th>
                @Html.DisplayNameFor( model => model.PhoneNumber )
            </th>
            <th>
                @Html.DisplayNameFor( model => model.StreetAddress )
            </th>
            <th>
                @Html.DisplayNameFor( model => model.City )
            </th>
            <th>
                @Html.DisplayNameFor( model => model.State )
            </th>
            <th>
                @Html.DisplayNameFor( model => model.ZipCode )
            </th>
            <th>
                @Html.DisplayNameFor( model => model.County )
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor( modelItem => item.LastName )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.FirstName )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.PhoneNumber )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.StreetAddress )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.City )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.State.Description )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.ZipCode )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.County.Description )
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DemographicId" class="loader">View / Edit</a>
            </td>
        </tr>
}
    </tbody>
</table>

src/StCamillus/Views/Demographics/_AddEditPartial.cshtml
@model DemographicAddEditViewModel

<div class="form-horizontal">
    @if ( ViewBag.ChangesMade )
    {
        <div class="alert alert-success fade show" id="successMsg">
            Changes Saved!
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="Demographic.DemographicId" />

    <div class="form-group row">
        <label asp-for="Demographic.BarcodeId" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-2">
            @if ( ViewBag.AddEditMode == "Edit" )
            {
                <input readonly asp-for="Demographic.BarcodeId" class="form-control" />
            }
            else
            {
                <input asp-for="Demographic.BarcodeId" class="form-control" />
            }

        </div>
        <div class="form-check offset-lg-2 col-lg">
            @*Self Disclosure*@
            <input asp-for="Demographic.SelfDisclosure" class="form-check-input" />
            <label asp-for="Demographic.SelfDisclosure" class="form-check-label"></label>
        </div>
    </div>


    <div class="form-group row">
        <label asp-for="Demographic.LastName" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.LastName" class="form-control" data-toggle="tooltip" title="@Model.Demographic.LastName" />
        </div>
        <label asp-for="Demographic.FirstName" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.FirstName" class="form-control" data-toggle="tooltip" title="@Model.Demographic.FirstName" />
        </div>
        <label asp-for="Demographic.PhoneNumber" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.PhoneNumber" class="form-control" />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Demographic.Dob" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.Dob" class="form-control" />
        </div>
        <label asp-for="Demographic.FlattenedAge" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.FlattenedAge" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="Demographic.EthnicityId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="Demographic.EthnicityId" class="form-control" asp-items="ViewBag.EthnicityId"><option value=""></option></select>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Demographic.StreetAddress" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.StreetAddress" class="form-control" data-toggle="tooltip" title="@Model.Demographic.StreetAddress" />
        </div>
        <label asp-for="Demographic.City" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.City" class="form-control" />
        </div>
        <label asp-for="Demographic.StateId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="Demographic.StateId" class="form-control" asp-items="ViewBag.StateId"><option value=""></option></select>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Demographic.CountyId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="Demographic.CountyId" class="form-control" asp-items="ViewBag.CountyId"><option value=""></option></select>
        </div>
        <label asp-for="Demographic.ZipCode" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.ZipCode" class="form-control" />
        </div>
        <label asp-for="Demographic.OriginCountryId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="Demographic.OriginCountryId" class="form-control" asp-items="ViewBag.OriginCountryId"><option value=""></option></select>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Demographic.MarriageStatusId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="Demographic.MarriageStatusId" class="form-control" asp-items="ViewBag.MarriageStatusId"><option value=""></option> </select>
        </div>
        <label asp-for="Demographic.TotalFamilyMembers" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.TotalFamilyMembers" class="form-control" />
        </div>
        <label asp-for="Demographic.Adults" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.Adults" class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Demographic.BiWeeklyIncomeId" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-2">
            <select asp-for="Demographic.BiWeeklyIncomeId" class="form-control" asp-items="ViewBag.BiWeeklyIncomeId"><option value=""></option></select>
        </div>
        <label asp-for="Demographic.Children" class="col-lg text-lg-right"></label>
        <div class="col-lg-2">
            <input asp-for="Demographic.Children" class="form-control" />
        </div>
        <div class="form-check col-1">
            <input asp-for="Demographic.ChildrenZeroToTwo" class="form-check-input" />
            <label asp-for="Demographic.ChildrenZeroToTwo" class="form-check-label"></label>
        </div>
        <div class="form-check col-1">
            <input asp-for="Demographic.ChildrenThreeToFive" class="form-check-input" />
            <label asp-for="Demographic.ChildrenThreeToFive" class="form-check-label"></label>
        </div>
        <div class="form-check col-1">
            <input asp-for="Demographic.ChildrenSixToFourteen" class="form-check-input" />
            <label asp-for="Demographic.ChildrenSixToFourteen" class="form-check-label"></label>
        </div>
        <div class="form-check col-1">
            <input asp-for="Demographic.ChildrenFifteenToEighteen" class="form-check-input" />
            <label asp-for="Demographic.ChildrenFifteenToEighteen" class="form-check-label"></label>
        </div>
    </div>
    <div class="form-group row">
        <div class=" offset-lg-1 col-lg-3">
            <label asp-for="Needs"></label>
            <select asp-for="SelectedNeedIds" multiple="multiple" class="form-control" asp-items="@Model.Needs"></select>
        </div>
        <div class="col-lg-4 offset-lg-2">
            <label asp-for="Demographic.Note"></label>
            <textarea asp-for="Demographic.Note" class="form-control" rows="4"></textarea>
        </div>
    </div>
</div>
<div class="form-group row">
    <div class="offset-lg-3 col-lg">
        <input type="submit" value="Save Changes" class="btn btn-success" />
    </div>
    @if ( ViewBag.AddEditMode == "Edit" )
    {
        <label asp-for="MostRecentDistributionDate" class="col-lg text-lg-right"></label>
        <div class="col-lg"><input asp-for="MostRecentDistributionDate" title="MostRecentDistributionDate" class="form-control" disabled="disabled" /></div>
        <div class="col-lg">
            <a id="distroButton" class="btn @Model.RecordDistroClass my-1 loader" asp-action="Create" asp-controller="Distribution" asp-route-id="@Model.Demographic.DemographicId" data-toggle="tooltip" title="@Model.RecordDistroToolTip">Record a Distribution</a>
        </div>
        <div class="col-lg">
            <a class="btn btn-dark my-1 loader" asp-action="AddEditByDemographicId" asp-controller="MannaData" asp-route-id="@Model.Demographic.DemographicId">Add/Edit Manna Data</a>
        </div>
    }
</div>