src/StCamillus/Controllers/DemographicsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StCamillus.Models;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using StCamillus.Data.Repositories;
using System.Collections.Generic;

namespace StCamillus.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "User Admin, Silver Spring, Langley Park")]
    public class DemographicsController : Controller
    {
        private readonly StCamillusContext _context;
        private readonly ITempDataDictionaryFactory _tempDataFactory;

        public DemographicsController(StCamillusContext context, ITempDataDictionaryFactory tempDataFactory)
        {
            _context = context;
            _tempDataFactory = tempDataFactory;
        }

        //// GET: Demographics
        //public async Task<IActionResult> Index()
        //{
        //    var demographics = _context.Demographic;
        //    return View(await demographics.ToListAsync());
        //}

        // GET: Demographics/Create
        public IActionResult Create()
        {
            ViewBag.ChangesMade = false;
            AddSelectLists();
            var viewModel = new DemographicAddEditViewModel { Demographic = new Demographic()};
            AddNeedsMultiSelect(viewModel);
            return View(viewModel);
        }

        // POST: Demographics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Demographic,Demographic.Adults,Demographic.Age,Demographic.BarcodeId,Demographic.BiWeeklyIncomeId,Demographic.Children,Demographic.ChildrenFifteenToEighteen,Demographic.ChildrenSixToFourteen,Demographic.ChildrenThreeToFive,Demographic.ChildrenZeroToTwo,Demographic.City,Demographic.CountyId,Demographic.Dob,Demographic.EthnicityId,Demographic.FirstName,Demographic.LastName,Demographic.MarriageStatusId,Demographic.Note,Demographic.OriginCountryId,Demographic.PhoneNumber,Demographic.SelfDisclosure,Demographic.StateId,Demographic.StreetAddress,Demographic.TotalFamilyMembers,Demographic.ZipCode,SelectedNeedIds,Needs")] DemographicAddEditViewModel viewModel)
        {
            if (_context.Demographic.Any(d => d.BarcodeId == viewModel.Demographic.BarcodeId))
            {
                ModelState.AddModelError("Card ID", "Card ID is already in use. Please search for the Card ID and modify the existing Demographic.");
            }

            if (ModelState.IsValid)
            {
                _context.Add(viewModel.Demographic);
                await _context.SaveChangesAsync();

                var demographic = await _context.Demographic.SingleOrDefaultAsync(m => m.BarcodeId == viewModel.Demographic.BarcodeId);
                if (demographic == null)
                {
                    return NotFound();
                }

                var demographicMultiValues = DemographicMultiValueRepository.GetDemographicMultiValues(_context, demographic.DemographicId);
                foreach (var need in LookupValueRepository.GetNeedsLookupValues(_context))
                {
                    var needId = need.LookupValueId;

                    if (viewModel.SelectedNeedIds != null && viewModel.SelectedNeedIds.Contains(needId) && !DemographicMultiValueRepository.DemographicMultiValueExists(_context, demographic.DemographicId, needId))
                    {
                        _context.Add(new DemographicMultiValue { DemographicId = demographic.DemographicId, LookupValueId = needId });
                    }
                }
                await _context.SaveChangesAsync();

                return RedirectToAction("Edit", new { id = demographic.DemographicId });
            }

            ViewBag.ChangesMade = false;
            AddSelectLists();
            AddNeedsMultiSelect(viewModel);
            return View(viewModel);
        }

        // GET: Demographics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if ( id == null )
            {
                return NotFound();
            }

            var demographic = await _context.Demographic.Include( d => d.Distributions ).SingleOrDefaultAsync( m => m.DemographicId == id );
            demographic.DemographicMultiValue = new HashSet<DemographicMultiValue>( DemographicMultiValueRepository.GetDemographicMultiValues( _context, demographic.DemographicId ) );

            if ( demographic == null )
            {
                return RedirectToAction( "Find", new { id, notFound = true } );
            }

            Distribution lastDistro = await GetLastDistro( demographic.DemographicId );

            ViewBag.ChangesMade = false;
            AddSelectLists();

            var viewModel = new DemographicAddEditViewModel { Demographic = demographic, MostRecentDistributionDate = lastDistro?.DistributionDate };
            AddNeedsMultiSelect( viewModel );
            return View( viewModel );
        }

        // POST: Demographics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Demographic,Demographic.DemographicId,Demographic.Adults,Demographic.Age,Demographic.BarcodeId,Demographic.BiWeeklyIncomeId,Demographic.Children,Demographic.ChildrenFifteenToEighteen,Demographic.ChildrenSixToFourteen,Demographic.ChildrenThreeToFive,Demographic.ChildrenZeroToTwo,Demographic.City,Demographic.CountyId,Demographic.Dob,Demographic.EthnicityId,Demographic.FirstName,Demographic.LastName,Demographic.MarriageStatusId,Demographic.Note,Demographic.OriginCountryId,Demographic.PhoneNumber,Demographic.SelfDisclosure,Demographic.StateId,Demographic.StreetAddress,Demographic.TotalFamilyMembers,Demographic.ZipCode,SelectedNeedIds,Needs")] DemographicAddEditViewModel viewModel)
        {
            ViewBag.ChangesMade = false;
            if (id != viewModel.Demographic.DemographicId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var demographicMultiValues = DemographicMultiValueRepository.GetDemographicMultiValues(_context, viewModel.Demographic.DemographicId);//_context.DemographicMultiValue.Where(dmv => dmv.DemographicId.Equals(viewModel.Demographic.DemographicId));

                foreach (var need in LookupValueRepository.GetNeedsLookupValues(_context))
                {
                    var needId = need.LookupValueId;

                    if ((viewModel.SelectedNeedIds == null || !viewModel.SelectedNeedIds.Contains(needId)) && DemographicMultiValueRepository.DemographicMultiValueExists(_context, viewModel.Demographic.DemographicId, needId))
                    {
                        _context.Remove(demographicMultiValues.Single(dmv => dmv.DemographicId.Equals(viewModel.Demographic.DemographicId) && dmv.LookupValueId.Equals(needId)));
                    }

                    if (viewModel.SelectedNeedIds != null && viewModel.SelectedNeedIds.Contains(needId) && !DemographicMultiValueRepository.DemographicMultiValueExists(_context, viewModel.Demographic.DemographicId, needId))
                    {
                        _context.Add(new DemographicMultiValue { DemographicId = viewModel.Demographic.DemographicId, LookupValueId = needId });
                    }
                }

                try
                {

                    _context.Update(viewModel.Demographic);
                    await _context.SaveChangesAsync();
                    ViewBag.ChangesMade = true;
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DemographicExists(viewModel.Demographic.DemographicId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            AddSelectLists();
            Distribution lastDistro = await GetLastDistro( viewModel.Demographic.DemographicId );
            viewModel.MostRecentDistributionDate = lastDistro?.DistributionDate;
            AddNeedsMultiSelect( viewModel );
            return View(viewModel);
        }

        public ActionResult Find(int id = 0, bool notFound = false)
        {
            var model = new DemographicSearchViewModel();

            //this is where we send the user if she arrives at EditDemographic/5 when there is no Demographic with id = 5
            if (notFound)
            {
                model.BarcodeId = id;
                ModelState.AddModelError("", "Not found. Please try again.");
            }

            // If we got to this action because of a saved distribution, there should be a message if the save was successful.
            // Alert the user that the save worked.
            var tempData = _tempDataFactory.GetTempData(this.HttpContext);
            var successMessage = tempData["SuccessMessage"];

            if (null != successMessage)
            {
                ViewBag.SuccessMessage = successMessage.ToString();
            }
            AddSelectLists();
            ViewData["CountyId"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(2)), "LookupValueId", "Description");
            ViewData["StateId"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(1)), "LookupValueId", "Description");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

src/StCamillus/Controllers/MannaPickupController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StCamillus.Models;
using Microsoft.AspNetCore.Authorization;
using System;

namespace StCamillus.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "User Admin, Silver Spring, Langley Park")]
    public class MannaPickupController : Controller
    {
        private readonly StCamillusContext _context;

        public MannaPickupController(StCamillusContext context)
        {
            _context = context;    
        }

        //// GET: MannaPickup
        //public async Task<IActionResult> Index()
        //{
        //    var stCamillusContext = _context.MannaPickup.Include(m => m.MannaData).Include(m => m.PickupLocation);
        //    return View(await stCamillusContext.ToListAsync());
        //}

        // GET: MannaPickup/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mannaPickup = await _context.MannaPickup.SingleOrDefaultAsync(m => m.MannaPickupId == id);
            if (mannaPickup == null)
            {
                return NotFound();
            }

            return View(mannaPickup);
        }

        // GET: MannaPickup/Create/5 
        //id is the MannaDataId the new pickup should be associated with
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mannaPickup = new MannaPickup { MannaDataId = id.Value };
            var lastPickup = _context.MannaPickup.OrderByDescending( mp => mp.PickupDate ).FirstOrDefault( p => p.MannaDataId == id );
            ViewBag.LatestPickup = lastPickup == null ? "" : lastPickup.PickupDate.Value.ToString("MM/dd/yyyy");
            AddSelectLists();
            return View(mannaPickup);
        }

        // POST: MannaPickup/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MannaDataId,Notes,PickupDate,PickupLocationId")] MannaPickup mannaPickup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mannaPickup);
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "MannaData", new { id = mannaPickup.MannaDataId });
            }
            AddSelectLists();
            return View(mannaPickup);
        }

        // GET: MannaPickup/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mannaPickup = await _context.MannaPickup.SingleOrDefaultAsync(m => m.MannaPickupId == id);
            if (mannaPickup == null)
            {
                return NotFound();
            }
            ViewData["MannaDataId"] = mannaPickup.MannaDataId;
            AddSelectLists();
            return View(mannaPickup);
        }

        // POST: MannaPickup/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MannaPickupId,MannaDataId,Notes,PickupDate,PickupLocationId")] MannaPickup mannaPickup)
        {
            if (id != mannaPickup.MannaPickupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mannaPickup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MannaPickupExists(mannaPickup.MannaPickupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit", "MannaData", new { id = mannaPickup.MannaDataId });
            }
            ViewData["MannaDataId"] = mannaPickup.MannaDataId;
            AddSelectLists();
            return View(mannaPickup);
        }

        // GET: MannaPickup/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mannaPickup = await _context.MannaPickup.SingleOrDefaultAsync(m => m.MannaPickupId == id);
            if (mannaPickup == null)
            {
                return NotFound();
            }

            return View(mannaPickup);
        }

        // POST: MannaPickup/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mannaPickup = await _context.MannaPickup.SingleOrDefaultAsync(m => m.MannaPickupId == id);
            _context.MannaPickup.Remove(mannaPickup);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool MannaPickupExists(int id)
        {
            return _context.MannaPickup.Any(e => e.MannaPickupId == id);
        }

        private void AddSelectLists()
        {
            ViewData["PickupLocations"] = new SelectList(_context.LookupValue.Where(l => l.LookupCategoryId.Equals(15) && l.Visible.Equals(true)), "LookupValueId", "Description");
        }
    }
}

src/StCamillus/Views/MannaData/Create.cshtml
@model MannaData

@{
    ViewData["Title"] = "Manna Data";
    ViewData["SubTitle"] = "Add";
    ViewBag.AddEditMode = "Add";
    ViewBag.NewMannaDataCreated = false;
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create" class="dataEntry">

    @Html.Partial("_AddEditPartial")

</form>

src/StCamillus/Views/MannaData/Delete.cshtml
@model StCamillus.Models.MannaData

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MannaData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmergencyContactName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmergencyContactName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmergencyContactPhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmergencyContactPhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FoodStampDollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FoodStampDollars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FormulaType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FormulaType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsEmployed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsEmployed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsReceivingEnergyAssistance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsReceivingEnergyAssistance)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsUsingMedicaid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsUsingMedicaid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MonthlyGrossDollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MonthlyGrossDollars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NeedsDiabeticBox)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NeedsDiabeticBox)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NeedsVegetarianBox)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NeedsVegetarianBox)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberOfChildren)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberOfChildren)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OtherDollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OtherDollars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PrimaryLanguage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrimaryLanguage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SocialSecurityDisabilityInsuranceDollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SocialSecurityDisabilityInsuranceDollars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SocialSecurityInsuranceDollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SocialSecurityInsuranceDollars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tanfdollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tanfdollars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UnemploymentDollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UnemploymentDollars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.YearlyGrossDollars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.YearlyGrossDollars)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @*<a asp-action="Index">Back to List</a>*@
        </div>
    </form>
</div>

src/StCamillus/Views/MannaData/Edit.cshtml
@model MannaData

@{
    ViewData["Title"] = "Manna Data";
    ViewData["SubTitle"] = "Edit";
    ViewBag.AddEditMode = "Edit";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-controller="Demographics" asp-action="Edit" asp-route-id="@Model.DemographicId">Back to Household</a>
</p>


<form asp-action="Edit" class="dataEntry">

    @Html.Partial("_AddEditPartial")

</form>

src/StCamillus/Views/MannaData/_AddEditPartial.cshtml
@model MannaData
<div class="form-horizontal">
    <h4>@ViewData[ "SubTitle" ]</h4>
    @if ( ViewBag.ChangesMade )
    {
        <div class="alert alert-success fade show" id="successMsg">
            Changes Saved!
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    @if ( ViewBag.NewMannaDataCreated )
    {
        <div class="alert alert-success fade show">
            New Manna Data added! See the bottom of the page for adding a referral pickup.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="MannaDataId" />
    <input type="hidden" asp-for="DemographicId" />

    <div class="form-group row">
        <label asp-for="Demographic.BarcodeId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.BarcodeId" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="MannaDataId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="MannaDataId" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="Demographic.Dob" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.Dob" class="form-control" disabled="disabled" />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Demographic.LastName" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.LastName" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="Demographic.FirstName" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="Demographic.FirstName" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="EmailAddress" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="EmailAddress" class="form-control" />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="GenderId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="GenderId" class="form-control" asp-items="ViewBag.Genders"></select>
        </div>
        <label asp-for="EmergencyContactName" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="EmergencyContactName" class="form-control" />
        </div>
        <label asp-for="EmergencyContactPhone" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="EmergencyContactPhone" class="form-control" />
        </div>
    </div>

    <hr class="col-lg-12" />

    <div class="form-group row">
        <label asp-for="PrimaryLanguage" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="PrimaryLanguage" class="form-control" />
        </div>
        <label for="Ethnicity" class="col-lg text-lg-right">Ethnicity</label>
        <div class="col-lg">
            <input type="text" class="form-control" disabled="disabled" name="Ethnicity" id="Ethnicity" value="@ViewBag.Ethnicity" />
        </div>
        <label asp-for="RaceId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="RaceId" class="form-control" asp-items="ViewBag.Races"><option value=""></option></select>
        </div>
    </div>

    <div class=" form-group row">
        <label asp-for="Demographic.Children" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-2">
            <input asp-for="Demographic.Children" class="form-control" disabled="disabled" />
        </div>
        <label asp-for="Demographic.Adults" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-2">
            <input asp-for="Demographic.Adults" class="form-control" disabled="disabled" />
        </div>
    </div>

    <div class="form-group row">
        <div class="form-check col-xl-4">
            <input asp-for="NeedsDiabeticBox" class="form-check-input ml-4" />
            <label asp-for="NeedsDiabeticBox" class="form-check-label ml-5"></label>
            <input asp-for="NeedsVegetarianBox" class="form-check-input ml-4" />
            <label asp-for="NeedsVegetarianBox" class="form-check-label ml-5"></label>
        </div>
        <label asp-for="BabyFoodStageId" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <select asp-for="BabyFoodStageId" class="form-control" asp-items="ViewBag.BabyFoodStages"><option value=""></option></select>
        </div>
        <label asp-for="FormulaType" class="col-lg text-lg-right"></label>
        <div class="col-lg">
            <input asp-for="FormulaType" class="form-control" />
        </div>
    </div>

    <hr class="col-lg-12" />

    <div class="form-group row">
        <div class="form-check col-xl-3">
            <input asp-for="IsEmployed" class="form-check-input ml-4" />
            <label asp-for="IsEmployed" class="form-check-label ml-5"></label>
        </div>
        <label asp-for="EmploymentStatusId" class="col-lg-1 text-lg-right"></label>
        <div class="col-lg-2">
            <select asp-for="EmploymentStatusId" class="form-control" asp-items="ViewBag.EmploymentStatuses"><option value=""></option></select>
        </div>
        <label asp-for="MonthlyGrossDollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="MonthlyGrossDollars" class="form-control" />
        </div>
        <label asp-for="YearlyGrossDollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="YearlyGrossDollars" class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="FoodStampDollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="FoodStampDollars" class="form-control" />
        </div>
        <label asp-for="UnemploymentDollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="UnemploymentDollars" class="form-control" />
        </div>
        <label asp-for="SocialSecurityInsuranceDollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="SocialSecurityInsuranceDollars" class="form-control" />
        </div>
        <label asp-for="SocialSecurityDisabilityInsuranceDollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="SocialSecurityDisabilityInsuranceDollars" class="form-control" />
        </div>
    </div>

    <div class="form-group row">
        <div class="form-check col-xl-3">
            <input asp-for="IsUsingMedicaid" class="form-check-input ml-4" />
            <label asp-for="IsUsingMedicaid" class="form-check-label ml-5"></label>
            <input asp-for="IsReceivingEnergyAssistance" class="form-check-input ml-4" />
            <label asp-for="IsReceivingEnergyAssistance" class="form-check-label ml-5"></label>
        </div>
        <label asp-for="Tanfdollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="Tanfdollars" class="form-control" />
        </div>
        <label asp-for="OtherDollars" class="col-lg-2 text-lg-right"></label>
        <div class="col-lg-1">
            <input asp-for="OtherDollars" class="form-control" />
        </div>
        <label asp-for="TransportationId" class="col-lg-1 text-lg-right"></label>
        <div class="col-lg-2">
            <select asp-for="TransportationId" class="form-control" asp-items="ViewBag.ModesOfTransportation"><option value=""></option></select>
        </div>
    </div>

    <div class="form-group row">
    </div>
    <div class="form-group row">
        <div class="offset-2 col-lg">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
@if ( ViewBag.AddEditMode == "Edit" )
{
    <hr />

    <h3>Manna Referral Date</h3>
    <a asp-controller="MannaPickup" asp-action="Create" asp-route-id="@Model.MannaDataId">Request Referral</a>
    <div class="col-xl-6">
        <table class="table table-sm table-striped table-bordered" id="Pickups">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Pick-up Date</th>
                    <th scope="col">Pick-up Location</th>
                    <th scope="col">Notes</th>
                </tr>
            </thead>
            <tbody>
                @if ( Model != null )
                {
                    foreach ( MannaPickup pickup in Model.MannaPickups.OrderByDescending( p => p.PickupDate ) )
                    {
                        @Html.Partial( "_MannaPickupsGridPartial", pickup )
                    }
                }
            </tbody>
        </table>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync( "_ValidationScriptsPartial" );}
}

src/StCamillus/Views/MannaData/_MannaPickupsGridPartial.cshtml
@model MannaPickup

<tr>
    <th scope="row">@Html.DisplayFor(m => m.PickupDate)</th>
    <td>@Html.DisplayFor(m => m.PickupLocation.Description)</td>
    <td>@Html.DisplayFor(m => m.Notes)</td>
</tr>